unit list_hlp;

interface

const

  hc_adr_auteur          = 8;
  hc_calendrier          = 24;
  hc_check_boxes         = 28;
  hc_ch_date             = 11;
  hc_ch_direct           = 25;
  hc_ch_heure            = 10;
  hc_default_opt         = 34;
  hc_file_ch_dir         = 19;
  hc_file_dos_shell      = 20;
  hc_file_erase          = 18;
  hc_file_exit           = 21;
  hc_file_select         = 17;
  hc_file_selector       = 26;
  hc_horloge             = 27;
  hc_Impression          = 12;
  hc_Index               = 3;
  hc_Info_Borland        = 9;
  hc_input_line          = 31;
  hc_input_number        = 30;
  hc_listeur             = 22;
  hc_listeur_demo        = 23;
  hc_load_opt            = 33;
  hc_Menu_File_List      = 4;
  hc_Menu_Info           = 7;
  hc_Menu_Options        = 5;
  hc_msg_directives      = 15;
  hc_param_msg           = 14;
  hc_param_others        = 16;
  hc_param_printer       = 13;
  hc_radio_buttons       = 29;
  hc_save_opt            = 32;
  hc_smenu_parameters    = 6;

implementation

end.
